import argparse
import io
import os

import h5py
import numpy as np
import torch
import torch.nn as nn
from torchdrug import data, models
from tqdm import tqdm

EMBED_DIM = 3072


class StructureEmbedding(nn.Module):
    def __init__(self, device=None):
        super().__init__()
        self.run_device = device or ("cuda" if torch.cuda.is_available() else "cpu")

        self.gearnet_edge = models.GearNet(
            input_dim=21,
            hidden_dims=[512, 512, 512, 512, 512, 512],
            num_relation=7,
            edge_input_dim=59,
            num_angle_bin=8,
            batch_norm=True,
            concat_hidden=True,
            short_cut=True,
            readout="sum",
        )

        weight_path = "./model/angle_gearnet_edge.pth"
        state_dict = torch.load(weight_path, map_location="cpu", weights_only=True)
        self.gearnet_edge.load_state_dict(state_dict)

        self.gearnet_edge.to(self.run_device).eval()

    @torch.no_grad()
    def forward(self, graph_objects):
        proteins = graph_objects
        proteins = data.Protein.pack(proteins).to(self.run_device)
        output = self.gearnet_edge(
            proteins, proteins.node_feature.float(), all_loss=None, metric=None
        )
        return list(output["graph_feature"].unbind(dim=0))


def initialize_hdf5(hdf5_path):
    with h5py.File(hdf5_path, "w") as f:
        f.create_dataset("ids", (0,), maxshape=(None,), dtype="S100")
        f.create_dataset(
            "embeddings", (0, EMBED_DIM), maxshape=(None, EMBED_DIM), dtype=np.float32
        )


def append_to_hdf5(hdf5_path, new_ids, new_embeddings):
    with h5py.File(hdf5_path, "a") as f:
        old_size = f["embeddings"].shape[0]
        new_size = old_size + len(new_embeddings)
        f["ids"].resize((new_size,))
        f["embeddings"].resize((new_size, EMBED_DIM))
        f["ids"][old_size:new_size] = np.array(new_ids, dtype="S")
        f["embeddings"][old_size:new_size] = np.array(new_embeddings, dtype=np.float32)


def load_graph_batch(input_h5, start, end):
    with h5py.File(input_h5, "r") as f:
        ids = [x.decode("utf-8") if isinstance(x, bytes) else str(x) for x in f["ids"][start:end]]
        graph_bytes_batch = f["graphs"][start:end]
    graphs = []
    for graph_bytes in graph_bytes_batch:
        buffer = io.BytesIO(graph_bytes.tobytes())
        graph_obj = torch.load(buffer, map_location="cpu", weights_only=False)
        graphs.append(graph_obj)
    return ids, graphs


def parse_args():
    parser = argparse.ArgumentParser(
        description="Run GearNet embedding from graph HDF5 generated by set1_graph.py."
    )
    parser.add_argument(
        "--input_h5",
        type=str,
        default="/root/fsas/A_RAMMER/data/random_100_graph.h5",
        help="Input HDF5 path generated by set1_graph.py",
    )
    parser.add_argument(
        "--output_h5",
        type=str,
        default="/root/fsas/A_RAMMER/data/random_100_gearnet_embedding.h5",
        help="Output HDF5 file path to save GearNet graph embeddings",
    )
    parser.add_argument(
        "--batch_size", type=int, default=8, help="Batch size for inference."
    )
    return parser.parse_args()


def main():
    args = parse_args()
    if not os.path.isfile(args.input_h5):
        raise FileNotFoundError(f"Input HDF5 not found: {args.input_h5}")

    output_parent = os.path.dirname(args.output_h5) or "."
    os.makedirs(output_parent, exist_ok=True)
    initialize_hdf5(args.output_h5)

    model = StructureEmbedding(device=None)
    with h5py.File(args.input_h5, "r") as f:
        total_size = f["ids"].shape[0]
    if total_size == 0:
        raise RuntimeError(f"No graph data found in input h5: {args.input_h5}")

    for start in tqdm(range(0, total_size, args.batch_size), desc="GearNet embedding"):
        end = min(start + args.batch_size, total_size)
        batch_ids, batch_graphs = load_graph_batch(args.input_h5, start, end)
        embeddings = model(batch_graphs)
        batch_embeddings = [embedding.detach().cpu().numpy() for embedding in embeddings]

        if batch_embeddings and batch_embeddings[0].shape[0] != EMBED_DIM:
            raise ValueError(
                f"Unexpected embedding dim {batch_embeddings[0].shape[0]}, expected {EMBED_DIM}"
            )
        append_to_hdf5(args.output_h5, batch_ids, batch_embeddings)

    print(f"Done. Saved {total_size} embeddings to: {args.output_h5}")


if __name__ == "__main__":
    main()